name: CI/CD Pipeline

on:
  push:
    branches:
      - dev
      - main
  pull_request:
    branches:
      - dev
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Docker
      run: |
        sudo apt-get update
        sudo apt-get install -y docker.io
        sudo systemctl start docker
        sudo systemctl enable docker
        sudo apt-get install -y curl
        curl -L "https://github.com/docker/compose/releases/download/1.29.2/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
        sudo chmod +x /usr/local/bin/docker-compose
        docker --version
        docker-compose --version

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '14'

    - name: Install dependencies for frontend and backend
      run: |
        cd frontend
        npm install
        cd ../backend
        npm install

    - name: Run tests for frontend
      run: |
        cd frontend
        npm test

    - name: Run tests for backend
      run: |
        cd backend
        npm test

    - name: Build Docker images
      run: |
        docker-compose up --build -d

    - name: Push Docker images
      run: |
        docker-compose push
