name: CI/CD Pipeline

on:
  push:
    branches:
      - dev
      - master
  pull_request:
    branches:
      - dev
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Docker
      run: |
        sudo apt-get remove -y docker docker-engine docker.io containerd runc

        sudo apt-get update

        sudo apt-get install -y apt-transport-https ca-certificates curl software-properties-common

        curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo tee /etc/apt/trusted.gpg.d/docker.asc

        sudo add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable"

        sudo apt-get update
        sudo apt-get install -y docker-ce docker-ce-cli containerd.io

        docker --version

        curl -L "https://github.com/docker/compose/releases/download/1.29.2/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
        sudo chmod +x /usr/local/bin/docker-compose

        docker-compose --version

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '14'

    - name: Install dependencies for frontend and backend
      run: |
        cd frontend
        npm install
        cd ../backend
        npm install

    - name: Run tests for frontend
      run: |
        cd frontend
        npm test

    - name: Run tests for backend
      run: |
        cd backend
        npm test

    - name: Build Docker images
      run: |
        docker-compose up --build -d

    - name: Push Docker images
      run: |
        docker-compose push

    - name: Configure Git identity
      run: |
        git config --global user.email "pauljouvanceau@gmail.com"
        git config --global user.name "Paul-420"

    - name: Merge dev into master (if applicable)
  if: github.ref == 'refs/heads/dev'
  run: |
    git fetch origin master
    git checkout master
    git merge dev --allow-unrelated-histories || true
    git checkout --theirs .
    git add .
    git commit -m "Merge dev into master - resolved conflicts by prioritizing dev"
    git push origin master
