name: CI/CD Pipeline

on:
  push:
    branches:
      - dev
      - master
  pull_request:
    branches:
      - dev
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Docker
      run: |
        # Supprimer les anciennes versions de Docker et containerd s'il y en a
        sudo apt-get remove -y docker docker-engine docker.io containerd runc

        # Mettre à jour la liste des paquets
        sudo apt-get update

        # Installer les dépendances nécessaires pour Docker
        sudo apt-get install -y apt-transport-https ca-certificates curl software-properties-common

        # Ajouter la clé GPG officielle de Docker
        curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo tee /etc/apt/trusted.gpg.d/docker.asc

        # Ajouter le dépôt stable de Docker
        sudo add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable"

        # Installer Docker
        sudo apt-get update
        sudo apt-get install -y docker-ce docker-ce-cli containerd.io

        # Vérifier que Docker est installé
        docker --version

        # Installer Docker Compose
        curl -L "https://github.com/docker/compose/releases/download/1.29.2/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
        sudo chmod +x /usr/local/bin/docker-compose

        # Vérifier que Docker Compose est installé
        docker-compose --version

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '14'

    - name: Install dependencies for frontend and backend
      run: |
        cd frontend
        npm install
        cd ../backend
        npm install

    - name: Run tests for frontend
      run: |
        cd frontend
        npm test

    - name: Run tests for backend
      run: |
        cd backend
        npm test

    - name: Build Docker images
      run: |
        docker-compose up --build -d

    - name: Push Docker images
      run: |
        docker-compose push

    - name: Merge dev to master (if applicable)
      if: github.ref == 'refs/heads/dev'
      run: |
        git fetch origin master
        git checkout master
        git merge dev
        git push origin master
